services:
  - type: web
    name: adverse-event-scraper
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
